In [15]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/kazi23/homeprices/homeprices.csv - Sheet1.csv

In [16]:
from sklearn import linear_model

In [17]:
df=pd.read_csv("/kaggle/input/datasets/kazi23/homeprices/homeprices.csv - Sheet1.csv")
df

   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [18]:
import math

medium_bedrooms=math.floor(df['bedrooms'].median())
print(medium_bedrooms)

3

In [19]:
df['bedrooms']=df['bedrooms'].fillna(medium_bedrooms)
df

   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [21]:
reg=linear_model.LinearRegression() # object of the model
reg.fit(df[['area','bedrooms','age']],df['price']) # train the model using the dataset

LinearRegression()

In [23]:
reg.coef_ # the weight to each variable

array([   137.25, -26025.  ,  -6825.  ])

In [24]:
reg.intercept_

np.float64(383724.9999999998)

In [26]:
reg.predict([[3000,3,40]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([444400.])